### ISSUE TITLE
Turn comments into self-explanatory code

### ISSUE THREAD

**Issue by KevinKhau** [CRSorin/nat-website#2]
Some quotes from _Clean Code_, Robert C. Martin
> The proper use of comments is to compensate for our failure to express ourself in code. Note that I used the word failure. I meant it. Comments are always failures. We must have them because we cannot always figure out how to express ourselves without them, but their use is not a cause for celebration.
<img width="581" alt="image" src="https://user-images.githubusercontent.com/16297343/196397636-f8146600-851d-487e-a7f8-5f0ed348c99f.png">
Given these statements, we thus need to remove comments as much as possible from the existing codebase.

**Comment by CRSorin** [comment]
Thanks for this!
I think I've addressed this issue: I removed all the commented out code and the comments for dead code.
