### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by KevinKhau** [CRSorin/nat-website#3]
> F4: Dead Function Methods that are never called should be discarded. Keeping dead code around is wasteful. Don’t be afraid to delete the function. Remember, your source code control system still remembers it.

> The problem with dead code is that after awhile it starts to smell. The older it is, the stronger and sourer the odor becomes. This is because dead code is not completely updated when designs change. It still compiles, but it does not follow newer conventions or rules. It was written at a time when the system was different. When you find dead code, do the right thing. Give it a decent burial. Delete it from the system.

Given these statements from _Clean Code_, Robert C. Martin, remove dead code from existing codebase.

**Comment by CRSorin** [comment]
Thanks for this! 
I tried my best to do this with the last commit. Please let me know if you believe I've overlooked something.
