### ISSUE TITLE
Factorize Youtube video displays

### ISSUE THREAD

**Issue by KevinKhau** [CRSorin/nat-website#5]
Always the same attributes, except for the link:

<img width="932" alt="image" src="https://user-images.githubusercontent.com/16297343/196429251-8e2786a3-d87a-4877-aa4c-4dc5c2b10b00.png">

Factorize and replace these calls. Additional attributes may be added in the future.

Remove deprecated frameborder="0"

**Comment by KevinKhau** [comment]
I have checked the Youtube iframe elements and have noticed the following attributes:
```
        width="560"
        height="315"
        title="YouTube video player"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
```
They don't seem to make any difference, are they deletable? @CRSorin

**Comment by CRSorin** [comment]
Indeed, they can all be removed.
